resolver: lts-13.19

packages:
- .
extra-deps:
- vectortiles-1.4.0
- protocol-buffers-2.4.11
- protocol-buffers-descriptor-2.4.11
- git: https://github.com/ondrap/text-icu.git
  commit: 2efdcf16d3ac0a11e1c7dc80f953a40fc5ae8f56
allow-newer: true
